packages:
  - 'apps/*'
  - 'packages/*'
  - 'functions'
  - 'services/*'

# Catalog for shared dependencies
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  next: latest
  
  # TypeScript
  typescript: ^5.3.3
  '@types/react': ^18.2.55
  '@types/react-dom': ^18.2.19
  '@types/node': ^20.11.16
  
  # Styling
  tailwindcss: ^3.4.1
  autoprefixer: ^10.4.17
  postcss: ^8.4.35
  clsx: ^2.1.1
  'tailwind-merge': ^3.3.1
  'lucide-react': ^0.545.0
  
  # Firebase
  firebase: ^12.3.0
  firebase-admin: ^13.5.0
  firebase-functions: ^4.8.0
  
  # AI/ML
  '@google-ai/generativelanguage': ^0.2.1
  openai: ^4.28.0
  
  # Database
  zod: ^3.22.4
  
  # Testing
  vitest: ^1.2.2
  '@testing-library/react': ^14.2.1
  '@playwright/test': ^1.41.2
  
  # Linting
  eslint: ^8.57.0
  prettier: ^3.2.5