# Production-specific values for Cortex DC
# Override default values for production environment

global:
  environment: production
  domain: cortex-dc.henryreed.ai
  imagePullSecrets:
    - name: gcr-json-key

web:
  replicaCount: 5  # Higher replica count for production

  image:
    pullPolicy: Always
    tag: latest  # Overridden by CI/CD

  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rate-limit: "200"
      nginx.ingress.kubernetes.io/limit-rps: "100"

  env:
    - name: NODE_ENV
      value: "production"
    - name: LOG_LEVEL
      value: "info"
    - name: ENABLE_ANALYTICS
      value: "true"

functions:
  replicaCount: 3

  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi

  autoscaling:
    minReplicas: 3
    maxReplicas: 10

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 2

costOptimization:
  preemptibleNodes: false
  clusterAutoscaling: true
