name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Frontend - Web UI
        - Backend - API/Services
        - Database - Data Layer
        - Auth - Authentication
        - Infrastructure - K8s/Docker
        - CI/CD - Pipelines
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocks major functionality
        - High - Important for user experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the use cases for this feature
      placeholder: |
        1. As a user, I want to...
        2. As an admin, I need to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups or examples from other applications
      placeholder: Drag and drop images or paste URLs

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical requirements or constraints?
      placeholder: |
        - API changes required
        - Database schema changes
        - Third-party integrations needed

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who will benefit from this feature? How many users?
      placeholder: |
        - Affects: [e.g., all users, admins only]
        - Estimated users: [e.g., 100+]
        - Business value: [e.g., reduces support tickets by 20%]

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] User can...
        - [ ] System validates...
        - [ ] Performance meets...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information above
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I am willing to contribute to this feature if needed
          required: false
