{{- if .Values.functions.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex-dc.fullname" . }}-functions
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cortex-dc.labels" . | nindent 4 }}
    {{- include "cortex-dc.functions.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.functions.service.type }}
  ports:
    - port: {{ .Values.functions.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cortex-dc.functions.selectorLabels" . | nindent 4 }}
{{- end }}
