{{- if .Values.functions.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-functions-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cortex-dc.labels" . | nindent 4 }}
    {{- include "cortex-dc.functions.selectorLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMaps.functions }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
