{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex-dc.fullname" . }}-web
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cortex-dc.labels" . | nindent 4 }}
    {{- include "cortex-dc.web.selectorLabels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cortex-dc.web.selectorLabels" . | nindent 4 }}
{{- end }}
