apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: cortex-dc
  labels:
    app: cortex-web
    component: frontend
data:
  # Application Configuration
  TARGET_ENV: "k8s"
  NODE_ENV: "production"
  PORT: "3000"

  # Feature Flags
  ENABLE_ANALYTICS: "true"
  ENABLE_TELEMETRY: "false"

  # Deployment Information
  APP_VERSION: "0.1.0"
  BUILD_DATE: "2025-10-15"

  # Logging
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

  # Performance
  MAX_OLD_SPACE_SIZE: "2048"

  # CORS Configuration (update with your domain)
  CORS_ORIGIN: "https://cortex.example.com"

  # NOTE: APP_BASE_URL and API_BASE_URL should be set in the deployment
  # as they vary by environment (dev/staging/prod)
