apiVersion: v1
kind: Service
metadata:
  name: functions-service
  namespace: cortex-dc
  labels:
    app: functions
    component: microservice
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "functions-backend-config"}'
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: http
    protocol: TCP
  selector:
    app: functions
    component: microservice
---
apiVersion: v1
kind: Service
metadata:
  name: functions-service-headless
  namespace: cortex-dc
  labels:
    app: functions
    component: microservice
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: functions
    component: microservice
